name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Upload the built app artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: amcc-app
          # A file, directory or wildcard pattern that describes what to upload
          path: amcc-app/target/*.jar
      - name: Upload the built protocol artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: amcc-protocol
          # A file, directory or wildcard pattern that describes what to upload
          path: amcc-protocol/target/*.jar
      - name: Upload the built plugin API artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: amcc-api
          # A file, directory or wildcard pattern that describes what to upload
          path: amcc-api/target/*.jar
      - name: Maven Dependency Tree Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v3.0.0
          
